apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    app: demoapp
    production: ready
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
      app: demoapp
      production: ready
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoapp
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: demoapp
        production: ready
    spec:
      containers:
      - name: demoapp
        image: bitspradp/cd_demo_spin:BUILD_NUMBER
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
