apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ornithology-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ornithology
    spec:
      containers:
      - name: ornithology
        image: otomato/ornithology:BUILD_NUMBER
        ports:
        - containerPort: 5000
        readinessProbe:
            httpGet:
                path: /ping
                port: 5000
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  strategy:
    type: Recreate
